name: TesseractCreative
version: '1.0-SNAPSHOT'
main: onl.tesseract.Creatif
api-version: '1.21'
depend: [ Vault,LuckPerms, TesseractCore ]


commands:
  menu:
    aliases: menu
    usage: "/menu"
    description: Ouvre le menu
    permission: tesseract.creatif.menu
  mondes:
    aliases: mondes
    usage: "/mondes"
    description: Ouvre le menu des mondes créa
    permission: tesseract.creatif.menu
  grades:
    aliases: grades
    usage: "/grades"
    description: Ouvre le menu des grades
    permission: tesseract.creatif.menu
  blocks:
    aliases: blocks
    usage: "/blocks"
    description: Ouvre le menu des blocs spéciaux
    permission: tesseract.creatif.menu
  outils:
    aliases: outils
    usage: "/outils"
    description: Ouvre le menu des outils de build
    permission: tesseract.creatif.menu
  commandes:
    aliases: commandes
    usage: "/commandes"
    description: Reçois un livre guide des commandes de build basiques
  boutique:
    aliases: boutique
    usage: "/boutique"
    description: Ouvre le menu de la boutique de Tesseract
  sethome:
    aliases: sethome
    usage: "/sethome"
    description: Crée un home pour le joueur.
  delhome:
    aliases: delhome
    usage: "/delhome"
    description: Supprime le home du joueur
  home:
    aliases: home
    usage: "/home"
    description: Teleporte le joueur au home
  scoreboard:
    aliases: scoreboard
    usage: "/scoreboard"
    description: Commandes du scoreboard
  nick:
    aliases: nick
    usage: "/nick"
    description: Mettre un surnom au joueur
  tpa:
    aliases: tpa
    usage: "/tpa"
    description: Se tp à un joueur
