name: TesseractCreative
version: '1.0-SNAPSHOT'
main: onl.tesseract.creative.Creative
api-version: '1.21'
depend: [ Vault,LuckPerms, TesseractCore ]


commands:
  menu:
    aliases: menu
    usage: "/menu"
    description: Ouvre le menu
    permission: tesseract.creatif.menu
  mondes:
    aliases: mondes
    usage: "/mondes"
    description: Ouvre le menu des mondes créa
    permission: tesseract.creatif.menu
  grades:
    aliases: grades
    usage: "/grades"
    description: Ouvre le menu des grades
    permission: tesseract.creatif.menu
  blocks:
    aliases: blocks
    usage: "/blocks"
    description: Ouvre le menu des blocs spéciaux
    permission: tesseract.creatif.menu
  outils:
    aliases: outils
    usage: "/outils"
    description: Ouvre le menu des outils de build
    permission: tesseract.creatif.menu
  commandes:
    aliases: commandes
    usage: "/commandes"
    description: Reçois un livre guide des commandes de build basiques
  boutique:
    aliases: boutique
    usage: "/boutique"
    description: Ouvre le menu de la boutique de Tesseract
  sethome:
    aliases: sethome
    usage: "/sethome"
    description: Crée un home pour le joueur.
  delhome:
    aliases: delhome
    usage: "/delhome"
    description: Supprime le home du joueur
  home:
    aliases: home
    usage: "/home"
    description: Teleporte le joueur au home
  scoreboard:
    aliases: scoreboard
    usage: "/scoreboard"
    description: Commandes du scoreboard
  staff:
    aliases: staff
    usage: "/staff"
    description: Commandes staff
    permission: tesseract.staff
  nick:
    aliases: nick
    usage: "/nick"
    description: Mettre un surnom au joueur
    permission: tesseract.creatif.nick
  tpa:
    aliases: tpa
    usage: "/tpa"
    description: Se tp à un joueur
  tpahere:
    aliases: tpahere
    usage: "/tpahere"
    description: Téléporter un joueur à soi
  speed:
    aliases: speed
    usage: "/speed"
    description: Permet de modifier sa speed
  top:
    aliases: top
    usage: "/top"
    description: Permet de se tp au point le plus haut
  back:
    aliases: back
    usage: "/back"
    description: Revenir au dernier emplacement avant tp
  tp:
    usage: "/tp"
    permission: tesseract.creatif.tp
  give:
    usage: "/give"
    permission: tesseract.creatif.give
  gamemode:
    usage: "/gamemode"
    aliases: gm
    permission: tesseract.creatif.gamemode
  hat:
    aliases: hat
    usage: "/hat"
    permission: tesseract.creatif.hat
    description: Mettre sur la tête l'objet en main
  ec:
    aliases: ec
    usage: "/ec"
    permission: tesseract.creatif.ec
  spawn:
    aliases: spawn
    usage: "/spawn"
    description: Se tp au spawn Crea